### PR TITLE
Wincheck

### LINKED ISSUE #12: Win Check
We need to check if the move wins the game

### PR DESCRIPTION
**Pull request by Thatchants**

### CODE REVIEW

**Comment by fillain** [comment]
LGTM

**Comment by andrew-fiel** [comment]
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by Thatchants** [comment]
it("Check Tie", async () => {
            await FCInstance.createGame(bob.address, {value: 500});
            await FCInstance.connect(bob).accept(gameIds[0], 0, {value: 500});
            await FCInstance.move(gameIds[0], 1, { from: alice.address });
            for(var i = 0;i < 6;i+=2){
                var maxK = 6;
                if(i == 0) maxK = 5;
                for(var k = 0;k < 6;k++){
                    await FCInstance.connect(bob).move(gameIds[0], i, { from: bob.address });
                    await FCInstance.move(gameIds[0], i+1, { from: alice.address });
                }
            }
            for(var i = 0;i < 3;i++){
                await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
                if(i != 3){
                    await FCInstance.move(gameIds[0], 6, { from: alice.address });
                }else{
                    await expect(await FCInstance.move(gameIds[0], 3, { from: alice.address })).to.changeEtherBalance(alice, 500);
                }
            }
            
        });

**Comment by Thatchants** [comment]
it("Check Tie", async () => {
            await FCInstance.createGame(bob.address, {value: 500});
            await FCInstance.connect(bob).accept(gameIds[0], 0, {value: 500});
            await FCInstance.move(gameIds[0], 1, { from: alice.address });
            for(var i = 0;i < 6;i+=2){
                var maxK = 6;
                if(i == 0) maxK = 5;
                for(var k = 0;k < 6;k++){
                    await FCInstance.connect(bob).move(gameIds[0], i, { from: bob.address });
                    await FCInstance.move(gameIds[0], i+1, { from: alice.address });
                }
            }
            for(var i = 0;i < 3;i++){
                await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
                if(i != 3){
                    await FCInstance.move(gameIds[0], 6, { from: alice.address });
                }else{
                    await expect(await FCInstance.move(gameIds[0], 3, { from: alice.address })).to.changeEtherBalance(alice, 500);
                }
            }
            
        });

**Comment by Thatchants** [comment]
it("Check Tie", async () => {
            await FCInstance.createGame(bob.address, {value: 500});
            
            for(var i = 0;i < 3;i++){
                for(var k = 0;k < 3;k++){
                    if(k%2 == 0){
                        if(i == 0 && k == 0){
                            await FCInstance.connect(bob).accept(gameIds[0], 2*k, {value: 500});
                        }else{
                            await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        }
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                    }else{
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                    }
                }
            }
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
        });

**Comment by Thatchants** [comment]
it("Check Tie", async () => {
            await FCInstance.createGame(bob.address, {value: 500});
            
            for(var i = 0;i < 3;i++){
                for(var k = 0;k < 3;k++){
                    if(k%2 == 0){
                        if(i == 0 && k == 0){
                            await FCInstance.connect(bob).accept(gameIds[0], 2*k, {value: 500});
                        }else{
                            await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        }
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                    }else{
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                    }
                }
            }
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await expect(await FCInstance.move(gameIds[0], 6, { from: alice.address })).to.changeEtherBalance(alice, 500);
        });

**Comment by Thatchants** [comment]
it("Check Tie", async () => {
            await FCInstance.createGame(bob.address, {value: 500});
            
            for(var i = 0;i < 3;i++){
                for(var k = 0;k < 3;k++){
                    if(k%2 == 0){
                        if(i == 0 && k == 0){
                            await FCInstance.connect(bob).accept(gameIds[0], 2*k, {value: 500});
                        }else{
                            await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        }
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k+1, { from: alice.address });
                    }else{
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                        await FCInstance.connect(bob).move(gameIds[0], 2*k+1, { from: bob.address });
                        await FCInstance.move(gameIds[0], 2*k, { from: alice.address });
                    }
                }
            }
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await FCInstance.move(gameIds[0], 6, { from: alice.address });
            await FCInstance.connect(bob).move(gameIds[0], 6, { from: bob.address });
            await expect(await FCInstance.move(gameIds[0], 6, { from: alice.address })).to.changeEtherBalance(alice, 500);
        });

**Comment by andrew-fiel** [comment]
0x13ad4281ef916a79b31a4451C3b05136C5a2E9e6

**Comment by Thatchants** [comment]
export function parseBoard(s) {
    s = s.substring(2, s.length)
    
    let board = [];
    for(var i = 0;i < s.length-63;i+=64){
        board.push(parseInt(s.charAt(i+63, 16)));
    }
    
    let board2D = [];
    for(var i = 0;i < board.length;i+=7){
        board2D.push([board[i],board[i+1],board[i+2],board[i+3],board[i+4],board[i+5],board[i+6]]);
    }
    return board2D;
}

**Pull request merged**
